name: Deploy Next.js to EC2

on:
  push:
    branches:
      - production
    paths:
        - 'frontend/**'
        - '.github/workflows/frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create frontend .env
        run: echo "${{ secrets.FRONTEND_ENV }}" > .env.production

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: '.next/,package.json,public/,node_modules/'
          target: '/home/ubuntu/jobblog-production'

      - name: SSH and restart Next.js app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/jobblog-production
            npm install --production
            pm2 delete nextjs-app || true
            pm2 start npm --name "nextjs-app" -- start